-- SELECT * FROM grab.chuyendi;
-- DROP TABLE chuyendi
--  CREATE TABLE grab.chuyendi (
--  maChuyenDi varchar(25),
--  maTaiXe varchar(25),
--  maKH varchar(25),
--  diemDi varchar(25),
--  diemDen varchar(25),
--  chiPhi varchar(25),
--  thoiGian varchar(25),
--  maGiamGia varchar(25))
--  
-- INSERT INTO chuyendi (maChuyenDi, maTaiXe, maKH, diemDi, diemDen, chiPhi, thoiGian, maGiamGia)
-- VALUES ('C1','NV1', 'KH1', '136 Ho tung mau', '28 dich vong hau', '40.000VND', '15 phut', 'MGG10'),('C2','NV1', 'KH2', '79 Ho tung mau', '8 pham hung, me tri', '30.000VND', '15 phut', 'MGG15')
SELECT * FROM grab.chuyendi